# Site settings
encoding: utf-8
#网站标题
title: "ychost's first blog"
#头像下面的名字
author_name: "ychost"
email: ychost@outlook.com
description: ""
baseurl: ""
url: "http://blog.sudoyc.com/"
title_description: "当天生的爱好发展成为一个强烈的愿望时，一个人会以惊人的速度向着他的目标大跨步地奔去。——Nikola Tesla"
#title_image: "/avatar/avatar_Tesla.jpg"
#头像
author_avatar: "/avatar/avatar_sketch.jpg"
#网页统计工具
baidu_analytics: "http://sitecenter.baidu.com/"
#评论账户
#评论系统 畅言 or 友言
comment_os : no
#comment_os: changyan
#comment_os:uyan
github_repository: https://github.com/ychost/ychost.github.io
#分享连接
jiaThis: ok
post_limit: 5
# Social usernames/URLs
#twitter_username: _jacobtomlinson
link_weibo: http://weibo.com/SuDoYc
link_mail: mailto:ychost@outlook.com
link_qq: tencent://message/?uin=292538649
github_username:  ychost

# Footer
footer_left: "楔子 <i class=\"fa fa-heart\"></i>  <a target=\"_new\" href=\"http://weibo.com/SuDoY\">八千里路</a>"
footer_right: "&lt;/&gt; on <a target=\"_new \" href=\"https://github.com/ychost\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
#category支持中文，让日期命名文件夹
#在github上面这样做有bug,导致搜索，文章链接不可用,但不这样做本地又无法预览中文命名的_post
#最后修改了jekyll的系统配置文件，使得其本地支持中文命名的_post
#permalink: /:year/:month/:day/:title

exclude: [vendor]
