# Site settings
encoding: utf-8
#the web title
title: "ychost's first blog"
#host name
author_name: "ychost"
email: ychost@outlook.com
description: ""
baseurl: ""
url: "http://blog.sudoyc.com/"
title_description: "当天生的爱好发展成为一个强烈的愿望时，一个人会以惊人的速度向着他的目标大跨步地奔去。——Nikola Tesla"
#home avatar
#title_image: "/avatar/avatar_Tesla.jpg"
author_avatar: "/avatar/avatar_sketch.jpg"

#web_analytics tools
baidu_analytics: "http://sitecenter.baidu.com/"

##markdown theme
#soruce: https://github.com/rhiokim/markdown-css
#param: clearness-dark | solarized-dark | node-dark | metro-vibes-dark
md_theme: node-dark

##comment system
#param: changyan | uyan | no
comment_os: changyan

github_repository: https://github.com/ychost/ychost.github.io
##share links
#param ok | no
#jiaThis: ok

#limit the number of posts that sorted by time
post_limit: 5
#limit the number of posts that sorted by categories
post_limit_categories: 4
# Social usernames/URLs
link_weibo: http://weibo.com/SuDoYc
link_mail: mailto:ychost@outlook.com
link_qq: tencent://message/?uin=292538649

#github info
github_username:  ychost

# Footer
footer_left: "楔子 <i class=\"fa fa-heart\"></i>  <a target=\"_new\" href=\"http://weibo.com/SuDoYc\">八千里路</a>"
footer_right: "&lt;/&gt; on <a target=\"_new \" href=\"https://github.com/ychost\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#set the build _posts's path
permalink: pretty

exclude: [vendor]
